import js from '@eslint/js'
import globals from 'globals'
import tseslint from 'typescript-eslint'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import unusedImports from 'eslint-plugin-unused-imports'

/**
 * One linter. oxlint arrived with the Vite template and was removed when this config landed:
 * two linters means two rule sets, two config files, and two places a rule can be turned off
 * without anyone noticing.
 */
export default tseslint.config(
  {
    // Generated by orval from docs/api/openapi.json. Reviewing it is reviewing the generator's
    // output; the spec is the reviewed artefact. Regenerate rather than edit.
    ignores: ['dist', 'src/api/generated/**', 'node_modules'],
  },

  js.configs.recommended,
  tseslint.configs.recommendedTypeChecked,

  {
    files: ['**/*.{ts,tsx,js}'],
    languageOptions: {
      ecmaVersion: 2023,
      globals: globals.browser,
      parserOptions: {
        // The config files and the generator script are JavaScript and belong to no tsconfig
        // project. Allowing them by default keeps type-aware linting on for everything that does.
        projectService: {
          allowDefaultProject: ['*.js', 'scripts/*.js'],
        },
        tsconfigRootDir: import.meta.dirname,
      },
    },
    plugins: {
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
      'unused-imports': unusedImports,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      'react-refresh/only-export-components': ['warn', { allowConstantExport: true }],

      // Unused imports and variables are errors, not warnings — the standing rule for this
      // codebase from step 16 on. `_`-prefixed arguments are the documented escape hatch.
      '@typescript-eslint/no-unused-vars': 'off',
      'unused-imports/no-unused-imports': 'error',
      'unused-imports/no-unused-vars': [
        'error',
        { vars: 'all', args: 'after-used', argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],

      // A floating promise is a mutation whose failure nobody sees. Type-aware, which is why
      // typescript-eslint is here rather than a syntactic linter.
      '@typescript-eslint/no-floating-promises': 'error',

      'no-restricted-imports': [
        'error',
        {
          paths: [
            {
              /*
               * The `@phosphor-icons/react` barrel re-exports 1,512 icons under 3,045 names.
               * Production tree-shakes it away; development does not. Vite pre-bundles a bare
               * import of it into one chunk and serves the whole thing — measured at 16.78 MB
               * decoded, 64% of everything the dev server sent for a single page, costing 436 ms
               * of main-thread parse and execute unthrottled and 2.5 s at 6× CPU throttling.
               *
               * Nine icons were pulling all of it. `@/components/icons` imports each from its own
               * `dist/csr/<Name>` entry point instead; add a line there for a new one.
               *
               * ⚠️ WHAT THIS RULE CANNOT SEE: a deep import written directly at a call site —
               * `@phosphor-icons/react/dist/csr/Plus` — is not restricted, and is not a
               * performance problem either. It is still worth sending through the icons module in
               * review, so that the set of icons this product uses is countable in one file.
               */
              name: '@phosphor-icons/react',
              message:
                'Never import from the @phosphor-icons/react barrel: Vite dev does not tree-shake it and serves all 3,045 exports as one 16.78 MB module. Import from @/components/icons, which takes each icon from its own entry point.',
            },
          ],
        },
      ],

      'no-restricted-syntax': [
        'error',
        {
          /*
           * CLAUDE.md rule 5, expressed where it can be enforced. `<input type="number">` parses
           * through an IEEE-754 double, localises its decimal separator inconsistently, and
           * changes value on a mouse wheel. Every decimal field in NovoCore uses MoneyInput,
           * UnitCostInput, QuantityInput or RateInput — text inputs backed by decimal.js.
           *
           * ⚠️ WHAT THIS RULE CANNOT SEE — established by probing it, not assumed:
           * `<input {...{ type: 'number' }} />` and `<input type={someVariable} />` both pass.
           * An AST selector can only read what is written at the attribute, so a value assembled
           * anywhere else is invisible to it. Worth watching for in review — and the reason the
           * decimal components exist as the single obvious alternative, rather than this rule
           * being the only defence.
           */
          selector: 'JSXAttribute[name.name="type"][value.value="number"]',
          message:
            'Never <input type="number">: it loses precision on money and quantities. Use MoneyInput, UnitCostInput, QuantityInput or RateInput from @/components/decimal.',
        },
        {
          // The same attribute written as an expression — `type={'number'}` — which the selector
          // above does not match, because its value is a container rather than a literal.
          selector:
            'JSXAttribute[name.name="type"] > JSXExpressionContainer > Literal[value="number"]',
          message:
            'Never <input type="number">: it loses precision on money and quantities. Use MoneyInput, UnitCostInput, QuantityInput or RateInput from @/components/decimal.',
        },
        {
          /*
           * The same rule from the other direction: a wire value must never reach a float.
           *
           * The first version banned the bare `parseFloat` / `parseInt` calls only, which a probe
           * showed to be a spelling check rather than a rule — `Number.parseFloat(x)`, `Number(x)`
           * and `+x` all passed, and `Number(x)` is the one somebody would actually write.
           * `Number('9007199254740993.01')` is `9007199254740992`; `+'12.10' * 100` is
           * `1209.9999999999998`.
           *
           * Every spelling is banned. Where a genuine integer has to be read from text — a page
           * size out of a URL, say — disable this rule on the line and say why: converting a
           * COUNT is fine, converting a VALUE never is.
           */
          selector:
            'CallExpression[callee.name=/^(parseFloat|parseInt|Number)$/], ' +
            'CallExpression[callee.object.name="Number"][callee.property.name=/^parse(Float|Int)$/], ' +
            'CallExpression[callee.object.name="globalThis"][callee.property.name=/^parse(Float|Int)$/], ' +
            'UnaryExpression[operator="+"][argument.type!="Literal"]',
          message:
            'A NovoCore amount or quantity must never become a JavaScript number — it is an IEEE-754 double and cannot hold the value. Use Decimal from decimal.js via @/lib/decimal. If this is genuinely a count rather than a value, disable this rule on the line with a reason.',
        },
      ],
    },
  },

  {
    // Node-side tooling: vite/vitest/orval config and the generators under scripts/.
    files: ['*.config.{ts,js}', 'scripts/**/*.js'],
    languageOptions: {
      // Only the globals differ. `parserOptions` is deliberately not restated: doing so replaced
      // the `allowDefaultProject` above and left these very files with no project to parse in.
      globals: globals.node,
    },
  },

  {
    /*
     * Type-aware rules off for plain JavaScript.
     *
     * The config files and the paging-map generator are `.js` with no type information, so every
     * `JSON.parse` is an `any` and the type-aware rules report dozens of unsafe operations that
     * are simply "this file is JavaScript". Turning them off here is upstream's own guidance; the
     * syntactic rules, including the `<input type="number">` ban, still apply.
     */
    files: ['**/*.js'],
    extends: [tseslint.configs.disableTypeChecked],
  },

  {
    /*
     * shadcn's own components, written out by `npx shadcn add` and re-written by the next run.
     *
     * Two rules are relaxed rather than fought: `set-state-in-effect` fires on the upstream
     * `use-mobile` hook, and the fast-refresh rule fires on files that export a hook beside a
     * component. Fixing either in place would be undone by the next regeneration — and these are
     * upstream's files, not ours. Everything we write is held to the full set.
     */
    files: ['src/components/ui/**/*.tsx', 'src/hooks/use-mobile.ts'],
    rules: {
      'react-hooks/set-state-in-effect': 'off',
      'react-refresh/only-export-components': 'off',
    },
  },

  {
    // Tests read the OpenAPI spec and poke at generated output; both are legitimately `any`-ish.
    files: ['**/*.test.{ts,tsx}', 'src/test/**/*.{ts,tsx}'],
    rules: {
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-argument': 'off',
      '@typescript-eslint/no-unsafe-call': 'off',
    },
  },
)
