import js from '@eslint/js'
import globals from 'globals'
import tseslint from 'typescript-eslint'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import unusedImports from 'eslint-plugin-unused-imports'

/**
 * One linter. oxlint arrived with the Vite template and was removed when this config landed:
 * two linters means two rule sets, two config files, and two places a rule can be turned off
 * without anyone noticing.
 */
export default tseslint.config(
  {
    // Generated by orval from docs/api/openapi.json. Reviewing it is reviewing the generator's
    // output; the spec is the reviewed artefact. Regenerate rather than edit.
    ignores: ['dist', 'src/api/generated/**', 'node_modules'],
  },

  js.configs.recommended,
  tseslint.configs.recommendedTypeChecked,

  {
    files: ['**/*.{ts,tsx,js}'],
    languageOptions: {
      ecmaVersion: 2023,
      globals: globals.browser,
      parserOptions: {
        // The config files and the generator script are JavaScript and belong to no tsconfig
        // project. Allowing them by default keeps type-aware linting on for everything that does.
        projectService: {
          allowDefaultProject: ['*.js', 'scripts/*.js'],
        },
        tsconfigRootDir: import.meta.dirname,
      },
    },
    plugins: {
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
      'unused-imports': unusedImports,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      'react-refresh/only-export-components': ['warn', { allowConstantExport: true }],

      // Unused imports and variables are errors, not warnings — the standing rule for this
      // codebase from step 16 on. `_`-prefixed arguments are the documented escape hatch.
      '@typescript-eslint/no-unused-vars': 'off',
      'unused-imports/no-unused-imports': 'error',
      'unused-imports/no-unused-vars': [
        'error',
        { vars: 'all', args: 'after-used', argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],

      // A floating promise is a mutation whose failure nobody sees. Type-aware, which is why
      // typescript-eslint is here rather than a syntactic linter.
      '@typescript-eslint/no-floating-promises': 'error',

      'no-restricted-syntax': [
        'error',
        {
          // CLAUDE.md rule 5, expressed where it can be enforced. `<input type="number">` parses
          // through an IEEE-754 double, localises its decimal separator inconsistently, and
          // changes value on a mouse wheel. Every decimal field in NovoCore uses MoneyInput,
          // UnitCostInput, QuantityInput or RateInput — text inputs backed by decimal.js.
          selector:
            'JSXAttribute[name.name="type"][value.value="number"]',
          message:
            'Never <input type="number">: it loses precision on money and quantities. Use MoneyInput, UnitCostInput, QuantityInput or RateInput from @/components/decimal.',
        },
        {
          // The same rule from the other direction: a wire value must never reach a float.
          selector:
            'CallExpression[callee.name=/^(parseFloat|parseInt)$/]',
          message:
            'parseFloat/parseInt cannot represent a NovoCore amount or quantity. Use Decimal from decimal.js via @/lib/decimal.',
        },
      ],
    },
  },

  {
    // Node-side tooling: vite/vitest/orval config and the generators under scripts/.
    files: ['*.config.{ts,js}', 'scripts/**/*.js'],
    languageOptions: {
      // Only the globals differ. `parserOptions` is deliberately not restated: doing so replaced
      // the `allowDefaultProject` above and left these very files with no project to parse in.
      globals: globals.node,
    },
  },

  {
    /*
     * Type-aware rules off for plain JavaScript.
     *
     * The config files and the paging-map generator are `.js` with no type information, so every
     * `JSON.parse` is an `any` and the type-aware rules report dozens of unsafe operations that
     * are simply "this file is JavaScript". Turning them off here is upstream's own guidance; the
     * syntactic rules, including the `<input type="number">` ban, still apply.
     */
    files: ['**/*.js'],
    extends: [tseslint.configs.disableTypeChecked],
  },

  {
    /*
     * shadcn's own components, written out by `npx shadcn add` and re-written by the next run.
     *
     * Two rules are relaxed rather than fought: `set-state-in-effect` fires on the upstream
     * `use-mobile` hook, and the fast-refresh rule fires on files that export a hook beside a
     * component. Fixing either in place would be undone by the next regeneration — and these are
     * upstream's files, not ours. Everything we write is held to the full set.
     */
    files: ['src/components/ui/**/*.tsx', 'src/hooks/use-mobile.ts'],
    rules: {
      'react-hooks/set-state-in-effect': 'off',
      'react-refresh/only-export-components': 'off',
    },
  },

  {
    // Tests read the OpenAPI spec and poke at generated output; both are legitimately `any`-ish.
    files: ['**/*.test.{ts,tsx}', 'src/test/**/*.{ts,tsx}'],
    rules: {
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-argument': 'off',
      '@typescript-eslint/no-unsafe-call': 'off',
    },
  },
)
