/**
 * The one place an HTTP request leaves this application.
 *
 * Everything generated by orval routes through `apiRequest`, so the CSRF convention, the session
 * behaviour and the error shape are properties of the client rather than things each call site has
 * to remember. `auth.ts` uses it too, for the two endpoints the spec does not describe.
 */

/** The RFC 7807 body every NovoCore error carries — including the ones Spring raises itself. */
export interface ProblemDetail {
  status?: number
  title?: string
  detail?: string
}

/**
 * A refused request, carrying what the backend was willing to say about it.
 *
 * The distinction between a validation refusal and a permission refusal is deliberate on the
 * backend and preserved here: step 14 made a validation refusal explain itself and a permission
 * refusal say nothing, because an operator who cannot see why a document was refused cannot fix
 * it, while an explanation of a permission refusal describes internal state. `detail` is therefore
 * absent on a 403 by design, not by accident, and the UI must not present its absence as an error
 * in itself.
 */
export class ApiError extends Error {
  readonly status: number
  readonly detail: string | undefined
  readonly problem: ProblemDetail | undefined

  constructor(status: number, problem?: ProblemDetail) {
    super(problem?.detail ?? problem?.title ?? `Request failed with status ${status}`)
    this.name = 'ApiError'
    this.status = status
    this.detail = problem?.detail
    this.problem = problem
  }

  /** The session is gone or was never established. */
  get isUnauthenticated(): boolean {
    return this.status === 401
  }

  /** Authenticated, but the role does not hold the section grant this route requires. */
  get isForbidden(): boolean {
    return this.status === 403
  }
}

/**
 * Reads Spring Security's CSRF cookie.
 *
 * Readable by JavaScript by design — `CookieCsrfTokenRepository.withHttpOnlyFalse()` — because the
 * frontend has to echo it back, and that is safe: an attacker's site cannot read a cookie belonging
 * to another origin. The session cookie itself stays HttpOnly and is never touched here.
 *
 * The token is present before login: SecurityConfiguration opts out of deferred loading, so the
 * cookie is written on the first response, 401 included. Verified against the running stack rather
 * than assumed — a token that only appeared after authentication could not be sent with it.
 */
function csrfToken(): string | undefined {
  for (const cookie of document.cookie.split(';')) {
    const [name, ...rest] = cookie.trim().split('=')
    if (name === 'XSRF-TOKEN') {
      return decodeURIComponent(rest.join('='))
    }
  }
  return undefined
}

/** Anything that changes state has to carry the token; a GET must not need one. */
function isStateChanging(method: string): boolean {
  return !['GET', 'HEAD', 'OPTIONS', 'TRACE'].includes(method.toUpperCase())
}

async function readProblem(response: Response): Promise<ProblemDetail | undefined> {
  const contentType = response.headers.get('content-type') ?? ''
  if (!contentType.includes('json')) return undefined
  try {
    return (await response.json()) as ProblemDetail
  } catch {
    // A body that claims to be JSON and is not tells us nothing beyond the status code, which the
    // caller already has. Swallowing it here is not hiding an error; the ApiError still carries
    // the status.
    return undefined
  }
}

/** Notified whenever a request comes back 401, so the session can be dropped exactly once. */
type UnauthenticatedListener = () => void
let onUnauthenticated: UnauthenticatedListener | undefined

export function setUnauthenticatedHandler(listener: UnauthenticatedListener | undefined): void {
  onUnauthenticated = listener
}

export interface ApiRequestOptions {
  url: string
  method: string
  params?: Record<string, unknown> | undefined
  data?: unknown
  headers?: Record<string, string>
  signal?: AbortSignal | undefined
  /** Form-encoded rather than JSON — Spring Security's /login, and nothing else. */
  formEncoded?: boolean
  /** Bytes rather than JSON — attachment downloads. */
  responseType?: 'json' | 'blob'
}

function buildUrl(url: string, params?: Record<string, unknown>): string {
  if (!params) return url
  const search = new URLSearchParams()

  /**
   * Query parameters are scalars. A Date is serialised as an ISO date because that is what the
   * spec's `format: date` parameters expect; anything else non-scalar is a caller mistake and
   * says so, rather than reaching the backend as `[object Object]` and being refused there.
   */
  const asParameter = (value: unknown): string => {
    if (typeof value === 'string') return value
    if (typeof value === 'number' || typeof value === 'boolean') return String(value)
    if (value instanceof Date) return value.toISOString().slice(0, 10)
    throw new TypeError(`Query parameter is not a scalar: ${JSON.stringify(value)}`)
  }

  for (const [key, value] of Object.entries(params)) {
    if (value === undefined || value === null) continue
    if (Array.isArray(value)) {
      for (const item of value as unknown[]) search.append(key, asParameter(item))
    } else {
      search.append(key, asParameter(value))
    }
  }
  const query = search.toString()
  return query ? `${url}?${query}` : url
}

export async function apiRequest<T>(options: ApiRequestOptions): Promise<T> {
  const { url, method, params, data, headers = {}, signal, formEncoded, responseType } = options

  const requestHeaders: Record<string, string> = { Accept: 'application/json', ...headers }

  if (isStateChanging(method)) {
    const token = csrfToken()
    if (token) requestHeaders['X-XSRF-TOKEN'] = token
  }

  let body: BodyInit | undefined
  if (data !== undefined && data !== null) {
    if (formEncoded) {
      requestHeaders['Content-Type'] = 'application/x-www-form-urlencoded'
      body = new URLSearchParams(data as Record<string, string>).toString()
    } else if (data instanceof FormData) {
      // Content-Type is deliberately unset: the browser has to add the multipart boundary.
      body = data
    } else {
      requestHeaders['Content-Type'] = 'application/json'
      body = JSON.stringify(data)
    }
  }

  const response = await fetch(buildUrl(url, params), {
    method: method.toUpperCase(),
    headers: requestHeaders,
    body,
    signal: signal ?? null,
    // The dev proxy and production both serve the API from this origin, so 'same-origin' is
    // enough and 'include' would be a wider grant than anything here needs.
    credentials: 'same-origin',
  })

  if (!response.ok) {
    if (response.status === 401) onUnauthenticated?.()
    throw new ApiError(response.status, await readProblem(response))
  }

  if (response.status === 204 || response.headers.get('content-length') === '0') {
    return undefined as T
  }
  if (responseType === 'blob') {
    return (await response.blob()) as T
  }
  return (await response.json()) as T
}

/**
 * The signature orval generates against.
 *
 * orval passes one options object and expects a promise of the response body; keeping that shape
 * here means the generated hooks need no per-call configuration at all.
 */
export const apiMutator = <T>(options: ApiRequestOptions): Promise<T> => apiRequest<T>(options)

export default apiMutator
